version: '2.4'

services:
  frontend:
    labels:
      shipyard.route: '/'
    build: 'frontend'
    environment:
      CI: 'true'
      DANGEROUSLY_DISABLE_HOST_CHECK: 'true'
    env_file:
      - frontend/frontend.env
    volumes:
      - './frontend/src:/app/src'
      - './frontend/public:/app/public'
    ports:
      - '3000:3000'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  base:
    image: postgres:11.22-bullseye
    volumes:
      - 'shipyard-postgres:/var/lib/postgresql/data/pgdata'
  
  psql-remote:
    extends:
      service: base
    environment:
      CP_CONFIG_ENV: development
      CP_CONFIG_PURPOSE: use1
  
  psql-template-image:
    extends:
      service: base
    # image: postgres:${PSQL_VERSION::2}-bullseye  # Invalid interpolation format for "image" option
    environment:
      # SHIPYARD_EPHEMERAL: true # services.psql-template-image.environment.SHIPYARD_EPHEMERAL contains true, which is an invalid type, it should be a string, number, or a null
      CP_CONFIG_JVM_MAX_HEAP: 250M
      CP_CONFIG_ENV: development
      CP_CONFIG_PURPOSE: use1
    depends_on:
      frontend:
        condition: service_healthy
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD

  hello:
    labels:
      shipyard.job: true
    image: busybox
    command: 'echo "Hello and Goodbye World"'

  hello_cron:
    labels:
      shipyard.job: true
      shipyard.job.schedule: '*/2 * * * *'
      shipyard.job.restartPolicy: Never
      shipyard.job.backoffLimit: 2
      shipyard.job.activeDeadlineSeconds: 60
      shipyard.job.successfulJobsHistoryLimit: 5
      shipyard.job.failedJobsHistoryLimit: 3
      shipyard.job.concurrencyPolicy: Forbid
    image: busybox
    command: 'echo "Hello World"'

volumes:
  shipyard-nfs:
  shipyard-postgres:
